### ISSUE TITLE
Initial release

### ISSUE THREAD

**Issue by 4kimov** [sqids/sqids-haskell#1]
Hey @laserpants, thanks for getting this codebase going! I'm trying to get this out of the door, so have a few questions:

1. I've noticed some tests are not 1:1 with the spec. My Haskell knowledge is limited, is there any way to get them to cover the same scenarios?
2. I've added a basic README. Think you could help me fill in the examples?
3. Would you like to publish the package?

Anything else we're missing? If not, I can update the site whenever this is good to go!

Edit: 4. Is there a way to setup Github Actions for auto-testing? (so the badge shows tests are passing)

**Comment by laserpants** [comment]
Hi @4kimov,

Thanks for checking in. There is still a bit of work to be done here. I was initially pushing the code to a temporary repository under my own account, but I decided to move it here once access was enabled, even though it is not quite ready. Not sure if that was the idea? :thinking: Otherwise I could move the code back to a less visible place, or push everything on a `dev` branch in the meantime. What do you think, please? A preliminary timeline is to get this ready for more serious testing sometime this coming week.  

Approximate progress bar:
```
[==============================>                 ]
```

1. The tests are just sanity checks as this point, while still implementing the core encoding/decoding logic (decoding is mostly done). Certainly these must be replaced/complemented with the official tests.
2. I suggest that this will follow after verifying that the official tests pass.
3. Same as for previous item.
4. I will look into this as well.

**Comment by laserpants** [comment]
- [x] Finish implementation of encoding
- [x] Clean up/finalize API and project structure
- [x] Add "official" tests
- [x] Publish (on Hackage)
- [x] Set up GitHub actions (CI)
- [x] Update README file
- [ ] Comment code/API docs
---
- [ ] Release party in the Bahamas? :parasol_on_ground: :smile:

**Comment by 4kimov** [comment]
Hi @laserpants,

Great, thank you for the quick reply. I think at this point it's absolutely fine to keep going with the `main` branch, it's a brand new repo. Later once people start using it, we can be more detailed about it and create extra branches as needed :)

Everything you're doing is great! Keep it up & let me know how I can help 🙏

**Comment by 4kimov** [comment]
Just FYI: I adjusted the spec [to match Microsoft's](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/b/blacklist) a bit better, so [pushed an update](https://github.com/sqids/sqids-haskell/commit/196fc8fc861e2e2b743e80b64db2718585f5debf) to this repo as well.

**Comment by laserpants** [comment]
@4kimov: This is mostly done now. I have added all the tests from the spec, set up CI, published the package to [Hackage](https://hackage.haskell.org/package/sqids) and update the README-file. The docs can be improved, so I added a separate issue for that [here](https://github.com/sqids/sqids-haskell/issues/2). Feel free to re-open this ticket if you think something is still missing.

**Comment by 4kimov** [comment]
@laserpants I think your docs are excellent. They're so full of information & even have a gif. Well done 👏 

I've updated the website @ https://sqids.org/haskell. I don't see anything else to update for this repo (I also see you've gotten the tests to match the spec, which is great). Thank you for doing all of this!

For now looks like this repo is set. The next approximate steps are:
1. For me to give Js + Rust + Go a bit of a push
2. See if the org can get a few more popular languages going (doesn't have to be all 40 of them)
3. A few days/weeks from now start redirecting (for example from https://hashids.org/haskell/ to https://sqids.org/haskell?hashids)

🙏
